config/routes.rb
Rails.application.routes.draw do
  resources :videos

  devise_for :users, 
    path: '', 
    path_names: { 
      sign_in: 'entrar', 
      sign_out: 'sair', 
      password: 'secret', 
      confirmation: 'verification', 
      unlock: 'unblock', 
      registration: 'novo', 
      sign_up: 'cadastrar' }  

  get "play/:id", controller: "home", action: "play", as: "play"
  put "videos/updateview/:id", controller: "videos", action: "updateview", as: "updateview"
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :videos

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true         
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  has_one_attached :cover

  validates :name, presence: true
  validates :url, presence: true, format: { with: /\A(http(s)?:\/\/)(\S)*(\/)(\S)*(.m3u8)\z/i, :message => "Extensão inválida" }

	def update_quantity
    update_attribute(:quantity, self.quantity + 1)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
  before_action :configure_permitted_parameters, if: :devise_controller? 

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || videos_path
  end
  
  protected 

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update, keys: [:name]) 
  end 
 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @videos = Video.all.sort_by(&:id)
  end

  def play
    @video = Video.find(params[:id])
  end
  
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!, except: %i[ updateview ]

  before_action :set_video, only: %i[ show edit update destroy ]

  def updateview
    videoview = Video.find(params[:id])
    videoview.update_quantity
  end

  # GET /videos or /videos.json
  def index
    @videos = Video.where(user: current_user)
  end

  # GET /videos/1 or /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
    video = Video.find(params[:id])
    redirect_to videos_path unless current_user.id == video.user.id
  end

  # POST /videos or /videos.json
  def create
    @video = Video.new(name: video_params[:name], url: video_params[:url], user: current_user)

    respond_to do |format|
      if @video.save
        format.html { redirect_to videos_path }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to videos_path }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:name, :url, :cover)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/home/index.html.erb
<header>
  <div class="container">
    <h2 class="h1 mt-5 mb-3">Todo os Vídeos</h2>
  </div>
</header>

<main>
  <div class="container">
    <div class="row">
      <div class="card-deck">
        <% @videos.each do |video| %>
          <div class="mb-5">
            <%= link_to play_path(video), class: "text-dark text-decoration-none" do %>
            <div class="card card-video">
              <div class="card-header h4"><%= video.name %></div>
              <%#= image_tag video.cover, class:"card-body", alt: video.name unless !video.cover.attached? %>
              <% if video.cover.attached? %>
                <%= image_tag video.cover, class:"card-body", alt: video.name %>
              <% else %>
                <%= image_tag "/assets/thumb-video.png", class:"card-body", alt: video.name %>
              <% end %>
              <div class="card-body">
                <h5 class="card-title h6"><%= video.quantity > 0 ?  "#{video.quantity} Visualizações" : 'Seja o primeiro a assistir' %></h5>
              </div>
            </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/home/play.html.erb
<header>
  <div class="container d-flex justify-content-center">
    <h2 class="h1 mt-5 mb-3"><%= @video.name %></h2>
  </div>
</header>

<main>
  <div class="container d-flex justify-content-center">
    <div class="embed-responsive embed-responsive-16by9 mb-3 w-50">
      <video
        id="video-<%= @video.id %>"
        class="video-js vjs-default-skin embed-responsive-item"
        controls="controls"
        preload="metadata"
        width="640"
        height="264"
        poster="<%= @video.url %>"
        data-setup="{}"
        onplay="oViewCount('video-<%= @video.id %>', '<%= updateview_path %>')"
        onpause="onplay=''"
      >
        <source src="<%= @video.url %>" type="application/x-mpegURL" />
      </video>
    </div>
  </div>
  <div class="container d-flex justify-content-center">
    <p><%= @video.quantity > 0 ?  "#{@video.quantity} Visualizações" : 'Seja o primeiro a assistir' %></p>
  </div>

</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TesteNetshowme</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'main', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link href="https://vjs.zencdn.net/7.10.2/video-js.css" rel="stylesheet" />

    <!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
    <!-- <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script> -->

  </head>

  <body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark d-flex">
      <%= link_to "MsFlix", root_path, class: "navbar-brand text-title" %>
      <div class="ml-auto">
        <% if user_signed_in? %>
          <button class="btn btn-outline-primary">
            <%= link_to "Meus Vídeos", videos_path, class: "text-white text-decoration-none" %>
          </button>
        <% end %>
        <button class="btn btn-primary">
          <% if !user_signed_in? %>
            <%= link_to "Entrar", user_session_path, class: "text-white text-decoration-none" %>
          <% else %>
            <%= link_to "Sair", destroy_user_session_path, class: "text-white text-decoration-none", :method => :delete %>
          <% end %>
        </button>
      </div>
    </nav>
    
    <%= yield %>

    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag '/assets/main', 'data-turbolinks-track': 'reload' %>

    <script src="https://vjs.zencdn.net/7.10.2/video.min.js"></script>

  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" class="container alert alert-warning w-75 mt-5" role="alert">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-floating mb-3">
    <%= form.label "Nome", for: "nameInput" %>
    <%= form.text_field :name, class: "form-control", id: "nameInput", placeholder: "Nome do Vídeo" %>
  </div>

  <div class="form-floating mb-3">
    <%= form.label "URL", for: "urlInput" %>
    <%= form.text_field :url, class: "form-control", id: "urlInput", placeholder: "URL do Vídeo" %>
  </div>

  <div class="form-floating mb-3">
    <%= form.label "Capa", for: "coverInput" %>
    <%= form.file_field :cover, class: "form-control", id: "coverInput" %>
  </div>

  <div class="form-floating mb-3">
    <%= button_tag "Salvar", type: 'submit', class: "btn btn-primary" %>
    <%= link_to "Cancelar", videos_path, class: "btn btn-danger", "data-toggle": "tooltip", title: "Voltar" %>
  </div>

<% end %>

app/views/videos/edit.html.erb
<div class="container">

  <h1>Editar Video</h1>

  <%= render 'form', video: @video %>

</div>

app/views/videos/index.html.erb
<div class="table-responsive container">
  <h1 class="mt-5">Vídeos de <%= current_user.name %></h1>
  <table class="table table-striped table-hover mb-5">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Visualizações</th>
        <th>Url</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @videos.each do |video| %>
        <tr>
          <td><%= video.name %></td>
          <td><%= video.quantity %></td>
          <td><%= video.url %></td>
          <td><%= link_to 'Visualizar', play_path(video) %></td>
          <td><%= link_to 'Editar', edit_video_path(video) %></td>
          <td><%= link_to 'Apagar', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to "Novo", new_video_path, class: "btn btn-md btn-success", "data-toggle": "tooltip", title: "Novo Registro"%>
</div>

app/views/videos/new.html.erb
<div class="container">

  <h1>Novo Vídeo</h1>

  <%= render 'form', video: @video %>

</div>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @video.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @video.url %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>